@baseUrl = http://localhost:5000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyZjljMmM0LTRjN2EtMTFlYy1iZjdiLTAyNDJhYzEyMDAwMiIsImVtYWlsIjoiYWRtaW5AbG9jYWxob3N0LmNvbSIsImlhdCI6MTc5MTQzNDUzMSwiZXhwIjoxNzkxNDM1NDMxfQ.Oyseerwti3IgnCRj16JfQUIqa401TfpLWUNEGho4_dc

POST {{baseUrl}}/auth/login
content-type: application/json

{
    "email":"thong2@localhost.com",
    "password":"thong123"
}

#################
POST {{baseUrl}}/auth/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "email":"thong2@localhost.com",
    "username":"thong2",
    "fullName":"thong",
    "password":"thong123"
}

#################
GET {{baseUrl}}/auth/roles
content-type: application/json
Authorization: Bearer {{token}}

#################
POST {{baseUrl}}/auth/users/3f101555-3082-4588-aa3a-6428d5ae7350/roles
content-type: application/json
Authorization: Bearer {{token}}

{
   "rolesId":["ba06a758-ffac-4287-91e1-b2f2601dde84"]
}