POST http://localhost:5000/api/v1/auth/login
content-type: application/json

{
    "email":"thong1@localhost.com",
    "password":"thong123"
}

#################
POST http://localhost:5000/api/v1/auth/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyZjljMmM0LTRjN2EtMTFlYy1iZjdiLTAyNDJhYzEyMDAwMiIsImVtYWlsIjoiYWRtaW5AbG9jYWxob3N0LmNvbSIsImlhdCI6MTc5MTQyODQ5NywiZXhwIjoxNzkxNDI5Mzk3fQ.au6JxGzt0Ffxlps8K2nN41Jr10tDShqbFepU-yIE7j8

{
    "email":"thong2@localhost.com",
    "username":"thong2",
    "fullName":"thong",
    "password":"thong123"
}

